services:
  fluentd:
    image: fluent/fluent-bit:latest
    command: [ "fluentd", "-c", "/fluentd/etc/fluent-conf.yaml" ]
    volumes:
      - ./fluent-conf.yaml:/fluentd/etc/fluent-conf.yaml:ro
    ports:
      - "24224:24224"
